file_dir: ./test #dir with csv input files
save_dir: ./output #output dir
station_names: cwg #location of pixel for input
plot_names: [runoffmod, snowheight, runoffcomp, runoff3plot, sfctemptime, sfctempscatter, albedobefore, albedoafter, albedobands, xsecticetemp, xsecticetempdiff, xsecticetempspinnup, icetempH]
